-- ====================================================
-- Query 10: Customer Lifetime Value
-- Purpose: Calculate the total number of orders and
-- lifetime revenue generated by each customer.
-- ====================================================

SELECT
    customer_id,
    COUNT(order_id) AS total_orders,
    ROUND(SUM(order_total_value), 2) AS lifetime_value
FROM orders
GROUP BY customer_id
ORDER BY lifetime_value DESC;


-- ====================================================
-- Query 11: Delivery Performance Analysis
-- Purpose: Compare on-time and late deliveries by
-- counting orders and calculating average delay.
-- ====================================================

SELECT
    late_delivery,
    COUNT(*) AS total_orders,
    ROUND(AVG(delivery_delay_days), 2) AS average_delay_days
FROM orders
GROUP BY late_delivery;


-- ====================================================
-- Query 12: Payment Method Analysis
-- Purpose: Analyze payment methods based on the number
-- of transactions and total payment value.
-- ====================================================

SELECT
    payment_type,
    COUNT(*) AS total_payments,
    ROUND(SUM(payment_value), 2) AS total_payment_value
FROM payments
GROUP BY payment_type
ORDER BY total_payment_value DESC;


-- ====================================================
-- Query 13: Average Review Score by Product Category
-- Purpose: Determine customer satisfaction across
-- product categories using average review scores.
-- ====================================================

SELECT
    ct.product_category_name_english,
    ROUND(AVG(r.review_score), 2) AS average_review_score
FROM reviews r
JOIN orders o
    ON r.order_id = o.order_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN products p
    ON oi.product_id = p.product_id
JOIN category_translation ct
    ON p.product_category_name = ct.product_category_name
GROUP BY ct.product_category_name_english
ORDER BY average_review_score DESC;
